adapters:
  rubicon:
    enabled: true
    endpoint: http://exapi-us-east.rubiconproject.com/a/api/exchange.json?tk_sdc=us-east
    XAPI.Username: opsco
    XAPI.Password: OPE433NDOR
  ttx:
    enabled: true
    endpoint: https://ssc.33across.com/api/v1/s2s
    usersync:
      url: https://ic.tynt.com/r/d?m=xch&rt=html&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&ru=https%3A%2F%2Fx.yieldlift.com%2Fsetuid%3Fbidder%3Dttx%26uid%3D33XUSERID33X&id=zzz000000000002zzz
      cookieFamilyName: ttx
      type: redirect
      supportCors: true
  sovrn:
    enabled: true
    endpoint: http://ap.lijit.com/bidder
  appnexus:
    enabled: true
    endpoint: http://ib.adnxs.com/openrtb2
  emx:
    enabled: true
    endpoint: http://hb.emxdgt.com
  openx:
    enabled: true
    endpoint: http://rtb.openx.net/prebid
    del_domain: os4m-d.openx.net
  pubmatic:
    enabled: true
    endpoint: http://hbopenbid.pubmatic.com/translator?source=prebid-server
    publisher_id: 157898
  sonobi:
    enabled: true
    endpoint: https://apex.go.sonobi.com/prebid?partnerid=71d9d3d8af
  rhythmone:
    enabled: true
    endpoint: http://tag.1rx.io/rmp
    zone_id: 1r
    path: mvo
host-cookie:
  domain: yieldlift.com
metrics:
  prefix: prebid
auction:
  ad-server-currency: USD
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  filesystem:
    settings-filename: sample-app-settings.yaml
    stored-requests-dir: /var/tmp
    stored-imps-dir: /var/tmp
    stored-responses-dir: /var/tmp
gdpr:
  enabled: false
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
status-response: "ok"
http:
  port: 80
